name: "Scan Docker Image"
description: "Scan Docker image using Trivy"
inputs:
  image-name:
    description: "Name of the Docker image to scan"
    required: true
  image-tag:
    description: "Build image with tag"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Trivy
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.46.2_Linux-64bit.deb
        sudo dpkg -i trivy_0.46.2_Linux-64bit.deb

    - name: Scan Docker image
      shell: bash
      run: trivy image --exit-code 1 ${{ inputs.image-name }}:${{ inputs.image-tag }}
